#!/usr/bin/env bash

# Inputs (in minutes)
LOCK_MINS=${1:-10}
SCREEN_OFF_MINS=${2:-5}
SLEEP_MINS=${3:-60}

# Convert minutes to seconds
LOCK_SECS=$((LOCK_MINS * 60))
SCREEN_OFF_SECS=$((SCREEN_OFF_MINS * 60))
SLEEP_SECS=$((SLEEP_MINS * 60))

CONFIG_FILE="$HOME/.config/niri/hypridle.conf"

# Generate base configuration
if [ "$XDG_CURRENT_DESKTOP" = "niri" ]; then
    cat <<EOF > "$CONFIG_FILE"
# Generated by QuickShell Control Center - Do not edit manually

general {
    lock_cmd = quickshell -p ~/.config/niri/scripts/quickshell/Lock.qml
    before_sleep_cmd = loginctl lock-session
}
EOF
else
    cat <<EOF > "$CONFIG_FILE"
# Generated by QuickShell Control Center - Do not edit manually

general {
    lock_cmd = quickshell -p ~/.config/niri/scripts/quickshell/Lock.qml
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch "hl.dsp.dpms({ action = 'on' })"
}
EOF
fi

# Add lock listener if enabled (minutes > 0)
if [ "$LOCK_MINS" -gt 0 ]; then
cat <<EOF >> "$CONFIG_FILE"

listener {
    timeout = $LOCK_SECS
    on-timeout = loginctl lock-session
}
EOF
fi

# Add screen off listener if enabled (minutes > 0)
if [ "$SCREEN_OFF_MINS" -gt 0 ]; then
    if [ "$XDG_CURRENT_DESKTOP" = "niri" ]; then
        cat <<EOF >> "$CONFIG_FILE"

listener {
    timeout = $SCREEN_OFF_SECS
    on-timeout = niri msg action power-off-monitors
}
EOF
    else
        cat <<EOF >> "$CONFIG_FILE"

listener {
    timeout = $SCREEN_OFF_SECS
    on-timeout = hyprctl dispatch "hl.dsp.dpms({ action = 'off' })"
    on-resume = hyprctl dispatch "hl.dsp.dpms({ action = 'on' })"
}
EOF
    fi
fi

# Add sleep listener if enabled (minutes > 0)
if [ "$SLEEP_MINS" -gt 0 ]; then
cat <<EOF >> "$CONFIG_FILE"

listener {
    timeout = $SLEEP_SECS
    on-timeout = systemctl suspend
}
EOF
fi

# Restart hypridle to apply the new configuration
killall hypridle || true
hypridle -c "$CONFIG_FILE" > /dev/null 2>&1 &
